/* GENERATED by the back office — edit data/portfolio-data.json (or use the back office), not this file. */
window.SITE = {
  "name": "Zakariae Chelle",
  "email": "zakariaechelle2001@gmail.com",
  "academicEmail": "Zakariae.Chelle@emsi-edu.ma",
  "github": "https://github.com/ZAKARIAE48CHELLE",
  "linkedin": "https://www.linkedin.com/in/zakariae-chelle",
  "cv": {
    "en": "resources/CV/CHELLE_ZAKARIAE_ENG.pdf",
    "fr": "resources/CV/CHELLE_ZAKARIAE_FR.pdf"
  },
  "projects": {
    "localops": {
      "github": "",
      "demo": "",
      "report": ""
    },
    "digitaltwin": {
      "github": "",
      "demo": "",
      "report": ""
    },
    "auramarket": {
      "github": "",
      "demo": "",
      "report": ""
    },
    "skin": {
      "github": "",
      "demo": "",
      "report": ""
    },
    "proxmox": {
      "github": "",
      "demo": "",
      "report": ""
    },
    "bank": {
      "github": "",
      "demo": "",
      "report": ""
    }
  }
};
