const links={portfolio:'https://zakariae48chelle.github.io/zakariae-chelle/',github:'https://github.com/ZAKARIAE48CHELLE',linkedin:'https://www.linkedin.com/in/zakariae-chelle',cv:'#',emailPrimary:'mailto:zakariaechelle2001@gmail.com'};
const projects=[
{key:'localOps',title:'LocalOps AI',subtitle:'Privacy-Preserving Incident Triage & Root Cause Analysis',category:'AI / LLMOps',featured:true,description:'A local incident triage and root cause analysis system based on a fine-tuned small language model with QLoRA, RAG over runbooks, FastAPI services, Prometheus monitoring, Docker deployment, and a web dashboard.',tags:['SLM','QLoRA','RAG','FastAPI','Prometheus','Docker'],highlights:['Fine-tuned local SLM for incident triage','RAG layer over operational runbooks','Monitoring and deployment-ready architecture']},
{key:'digitalTwin',title:'Digital Twin Client Classification',subtitle:'Dynamic Classification of Prospects & Clients',category:'Data Science / Business AI',featured:true,description:'An AI platform combining digital twins, RFM-ES/AHP scoring, CLV estimation, churn and conversion prediction, dynamic personas, Streamlit, PostgreSQL, LangGraph, and a governed local LLM.',tags:['Digital Twins','CLV','Churn','Streamlit','PostgreSQL','LangGraph'],highlights:['Dynamic client and prospect classification','CLV, churn and conversion modelling','Local LLM decision support']},
{key:'auraMarket',title:'AuraMarket',subtitle:'Intelligent Marketplace with Multi-Agent System',category:'Multi-Agent Systems',featured:true,description:'An intelligent marketplace platform integrating smart product search, user assistance, automated negotiation, dynamic offers, and suspicious activity detection through specialized agents.',tags:['Multi-Agent','Smart Search','Negotiation','Security','Marketplace'],highlights:['Buyer and seller negotiation agents','Dynamic offer generation','Suspicious activity detection']},
{key:'skinDisease',title:'Skin Disease Detection',subtitle:'Computer vision decision-support prototype',category:'Computer Vision',description:'CNN-based educational prototype that analyzes dermatological images and provides confidence scores for decision support. It is not a substitute for professional diagnosis.',tags:['CNN','TensorFlow','Keras','Medical AI','Image Classification']},
{key:'virtualization',title:'Virtualization / Cloud Solutions',subtitle:'Isolated internal network lab',category:'Infrastructure',description:'Design and deployment of an isolated internal network in a virtualized environment using the Proxmox VE Type 1 hypervisor.',tags:['Proxmox VE','Virtualization','Networking','Infrastructure']},
{key:'bankSimulator',title:'Bank Transaction Simulator',subtitle:'Java desktop application',category:'Software Engineering',description:'A Java application simulating account management, deposits, withdrawals, transaction history, object-oriented design, and concurrency handling.',tags:['Java','OOP','Concurrency','Desktop Application']}];
const skillGroups=[['AI / ML','◈',['Machine Learning','Deep Learning','NLP','Computer Vision','TensorFlow','Keras','PyTorch','Pandas']],['LLM Systems','✦',['Large Language Models','RAG','QLoRA','Ollama','AI Agents','Multi-Agent Systems','LangGraph','Local LLMs']],['Data Engineering','▤',['PostgreSQL','SQL','Hadoop / HDFS','Apache Spark','Apache Kafka','Data Processing','Dashboards']],['Backend & Architecture','⌘',['Python','Java','TypeScript','FastAPI','Spring Boot','Microservices','REST APIs','Docker','Prometheus']],['Frontend & Dashboards','▱',['Angular','Streamlit','HTML','CSS','JavaScript','Responsive UI','Dashboard Design']],['Design & Creative','◌',['Photoshop','Premiere Pro','Lightroom','Infographics','UI Polishing']]];
function card(p){const tags=p.tags.map(x=>`<span class="tag">${x}</span>`).join('');const highs=p.highlights?`<ul class="highlights">${p.highlights.map(x=>`<li>${x}</li>`).join('')}</ul>`:'';return `<article class="project-card ${p.featured?'featured':''} reveal"><span class="category">${p.category}</span><h3>${p.title}</h3><p class="subtitle">${p.subtitle}</p><p class="description">${p.description}</p><div class="tags">${tags}</div>${highs}<div class="project-links"><a href="#" class="project-link" title="Project link coming soon">GitHub ↗</a><a href="#" class="project-link" title="Project link coming soon">Details ↗</a></div></article>`}
document.getElementById('featured-projects').innerHTML=projects.filter(p=>p.featured).map(card).join('');document.getElementById('all-projects').innerHTML=projects.filter(p=>!p.featured).map(card).join('');document.getElementById('skills-grid').innerHTML=skillGroups.map(([name,icon,tags])=>`<article class="skill-card reveal"><div class="skill-icon">${icon}</div><h3>${name}</h3><div class="skill-tags">${tags.map(x=>`<span>${x}</span>`).join('')}</div></article>`).join('');document.getElementById('year').textContent=new Date().getFullYear();
document.querySelectorAll('.github-link').forEach(a=>a.href=links.github);document.querySelectorAll('.linkedin-link').forEach(a=>{a.href=links.linkedin});document.querySelectorAll('.cv-link').forEach(a=>{a.href=links.cv});document.querySelectorAll('.project-link').forEach(a=>a.addEventListener('click',e=>e.preventDefault()));
const navbar=document.getElementById('navbar');window.addEventListener('scroll',()=>navbar.classList.toggle('scrolled',window.scrollY>15));const toggle=document.querySelector('.menu-toggle'),menu=document.getElementById('nav-links');toggle.addEventListener('click',()=>{const open=menu.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});menu.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');toggle.setAttribute('aria-expanded','false')}));const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const uiTranslations={
 en:{nav:['Home','About','Projects','Skills','Experience','Contact'],cv:'Download CV ↗',hero:'Hi, I’m <em>Zakariae</em> Chelle.',role:'Data & Artificial Intelligence Engineering Student',intro:'I build intelligent platforms combining machine learning, local LLMs, RAG, multi-agent systems, dashboards, APIs, and production-oriented software architecture.',view:'View Projects ↓',about:'Engineering useful intelligence.',project:'Featured projects',more:'Additional projects',skills:'Tools for the full system.',experience:'Building in real teams.',education:'Always learning.',contact:'Let’s build intelligent systems together.',email:'Email me ↗'},
 fr:{nav:['Accueil','À propos','Projets','Compétences','Expérience','Contact'],cv:'Télécharger le CV ↗',hero:'Bonjour, je suis <em>Zakariae</em> Chelle.',role:'Étudiant ingénieur en Données et Intelligence Artificielle',intro:'Je construis des plateformes intelligentes combinant apprentissage automatique, LLM locaux, RAG, systèmes multi-agents, tableaux de bord, API et architecture logicielle orientée production.',view:'Voir les projets ↓',about:'Concevoir une intelligence utile.',project:'Projets à la une',more:'Autres projets',skills:'Les outils du système complet.',experience:'Construire en équipe.',education:'Toujours apprendre.',contact:'Construisons des systèmes intelligents ensemble.',email:'M’écrire ↗'},
 es:{nav:['Inicio','Sobre mí','Proyectos','Habilidades','Experiencia','Contacto'],cv:'Descargar CV ↗',hero:'Hola, soy <em>Zakariae</em> Chelle.',role:'Estudiante de Ingeniería de Datos e Inteligencia Artificial',intro:'Creo plataformas inteligentes que combinan aprendizaje automático, LLM locales, RAG, sistemas multiagente, paneles, API y arquitectura de software orientada a producción.',view:'Ver proyectos ↓',about:'Ingeniería de inteligencia útil.',project:'Proyectos destacados',more:'Más proyectos',skills:'Herramientas para el sistema completo.',experience:'Construyendo en equipos reales.',education:'Siempre aprendiendo.',contact:'Construyamos sistemas inteligentes juntos.',email:'Escríbeme ↗'},
 ar:{nav:['الرئيسية','نبذة','المشاريع','المهارات','الخبرة','تواصل'],cv:'تحميل السيرة الذاتية ↗',hero:'مرحباً، أنا <em>زكرياء</em> الشلي.',role:'طالب هندسة البيانات والذكاء الاصطناعي',intro:'أبني منصات ذكية تجمع بين التعلم الآلي، ونماذج اللغة المحلية، وRAG، والأنظمة متعددة الوكلاء، ولوحات المعلومات، وواجهات البرمجة، وهندسة البرمجيات الجاهزة للإنتاج.',view:'عرض المشاريع ↓',about:'هندسة ذكاء مفيد.',project:'مشاريع مميزة',more:'مشاريع إضافية',skills:'أدوات للنظام الكامل.',experience:'البناء ضمن فرق حقيقية.',education:'التعلّم باستمرار.',contact:'لنبنِ أنظمة ذكية معاً.',email:'راسلني ↗'}
};
function applyLanguage(lang){const t=uiTranslations[lang]||uiTranslations.en;document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';localStorage.setItem('portfolio-language',lang);document.getElementById('language-button').textContent=`${lang.toUpperCase()} ▾`;document.querySelectorAll('#nav-links a').forEach((a,i)=>a.textContent=t.nav[i]);document.querySelectorAll('.cv-link').forEach(a=>a.textContent=t.cv);document.querySelector('.hero h1').innerHTML=t.hero;document.querySelector('.hero-role').textContent=t.role;document.querySelector('.hero-description').textContent=t.intro;document.querySelector('.hero-buttons .primary').textContent=t.view;const headings=document.querySelectorAll('.section-heading h2');headings[0].textContent=t.about;headings[1].textContent=t.project;headings[2].textContent=t.skills;headings[3].textContent=t.experience;headings[4].textContent=t.education;document.querySelector('.more-heading h2').textContent=t.more;document.querySelector('.contact h2').textContent=t.contact;document.querySelector('.contact .primary').textContent=t.email}
const languageButton=document.getElementById('language-button'),languageMenu=document.getElementById('language-menu');languageButton.addEventListener('click',()=>{const open=languageMenu.classList.toggle('open');languageButton.setAttribute('aria-expanded',open)});languageMenu.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>{applyLanguage(button.dataset.lang);languageMenu.classList.remove('open');languageButton.setAttribute('aria-expanded','false')}));applyLanguage(localStorage.getItem('portfolio-language')||'en');
